import 'package:mobile_create/app/data/models/product_model.dart';

List<ProductModel> productsMock = [
  ProductModel(
      productId: '1',
      productOwnerId: '1',
      productName: 'Bag',
      productDescription: 'Green',
      images: [],
      discount: 10,
      total: 100),
  ProductModel(
      productId: '2',
      productOwnerId: '2',
      productName: 'Bag',
      productDescription: 'Blue',
      images: [],
      discount: 10,
      total: 150),
  ProductModel(
      productId: '3',
      productOwnerId: '3',
      productName: 'T-shirts',
      productDescription: 'Colorful',
      images: [],
      discount: 10,
      total: 80),
  ProductModel(
      productId: '4',
      productOwnerId: '4',
      productName: 'Sneakers',
      productDescription: 'White',
      images: [],
      discount: 10,
      total: 350),
  ProductModel(
      productId: '5',
      productOwnerId: '5',
      productName: 'T-shirts',
      productDescription: 'Colorful',
      images: [],
      discount: 10,
      total: 70),
  ProductModel(
      productId: '6',
      productOwnerId: '6',
      productName: 'Shoes',
      productDescription: 'Orange',
      images: [],
      discount: 10,
      total: 120),
  ProductModel(
      productId: '7',
      productOwnerId: '7',
      productName: 'Shoes',
      productDescription: 'Blue',
      images: [],
      discount: 10,
      total: 180),
  ProductModel(
      productId: '8',
      productOwnerId: '8',
      productName: 'Watch',
      productDescription: 'black',
      images: [],
      discount: 10,
      total: 450),
  ProductModel(
      productId: '9',
      productOwnerId: '9',
      productName: 'Watch',
      productDescription: 'Golden',
      images: [],
      discount: 10,
      total: 700),
  ProductModel(
      productId: '10',
      productOwnerId: '10',
      productName: 'Notebook',
      productDescription: 'Acer',
      images: [],
      discount: 100,
      total: 5000),
  ProductModel(
      productId: '11',
      productOwnerId: '11',
      productName: 'Headphone',
      productDescription: 'JBL',
      images: [],
      discount: 10,
      total: 300),
  ProductModel(
      productId: '12',
      productOwnerId: '12',
      productName: 'Loudspeker',
      productDescription: 'JBL',
      images: [],
      discount: 10,
      total: 800),
  ProductModel(
      productId: '13',
      productOwnerId: '13',
      productName: 'Iphone 13',
      productDescription: 'White',
      images: [],
      discount: 10,
      total: 4000),
  ProductModel(
      productId: '14',
      productOwnerId: '14',
      productName: 'Camera Cannon',
      productDescription: 'Black',
      images: [],
      discount: 10,
      total: 4000),
  ProductModel(
      productId: '15',
      productOwnerId: '15',
      productName: 'Camera Cannon',
      productDescription: 'Black',
      images: [],
      discount: 10,
      total: 6000),
  ProductModel(
      productId: '16',
      productOwnerId: '16',
      productName: 'TV',
      productDescription: 'Black',
      images: [],
      discount: 10,
      total: 6000),
  ProductModel(
      productId: '17',
      productOwnerId: '17',
      productName: 'TV',
      productDescription: 'Black',
      images: [],
      discount: 10,
      total: 6000),
];
